version: '3.8'

services:
  zookeeper:
      image: wurstmeister/zookeeper:latest
      container_name: zookeeper
      ports:
        - "2181:2181"

  kafka:
      image: wurstmeister/kafka:latest
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper

  pytorch-notebook:
    image: pytorch/pytorch:latest
    container_name: pytorch_jupyter
    command: bash -c "pip install jupyter && jupyter notebook --ip=0.0.0.0 --no-browser --allow-root"
    volumes:
      - /home/lambda/Documents/titanic-online:/workspace  # Maps /home/lambda/Documents on the host to /workspace in the container
    ports:
      - "8888:8888"  # Expose Jupyter notebook port
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    ipc: host
